**⭐️ CREATING TENSORS**

In [2]:
import torch
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.zeros(3, 3)
tensor_3 = torch.rand(2, 2) # RANDOM VALUES B/W 0 AND 1
tensor_random = torch.rand(3, 3)
tensor_randint = torch.randint(0, 10, (3, 3))  # RANDOM INTS B/W 0 AND 10
print(tensor_1)
print(tensor_2)
print(tensor_3)
print(tensor_random)
print(tensor_randint)

tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5672, 0.6936],
        [0.5313, 0.6131]])
tensor([[0.7510, 0.7434, 0.2311],
        [0.7626, 0.9821, 0.0386],
        [0.8636, 0.4812, 0.2380]])
tensor([[2, 0, 6],
        [9, 1, 9],
        [4, 1, 9]])


**⭐️ TENSOR ARITHMETIC**

In [15]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)
print(a * b)
print(a - b)
print(a ** 2)
print(torch.sqrt(a))
print(a.matmul(b)) # SIMILAR TO print(torch.matmul(a,b))
print(a.sum())
a.add_(23) # IN PLACE ADDITION
print(a)
a.sub_(23) # IN PLACE SUBTRACTION
print(a)
a.mul_(23) # IN PLACE MULTIPLICATION
print(a)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([-3, -3, -3])
tensor([1, 4, 9])
tensor([1.0000, 1.4142, 1.7321])
tensor(32)
tensor(6)
tensor([24, 25, 26])
tensor([1, 2, 3])
tensor([23, 46, 69])


**⭐️ TENSOR CONVERSIONS**

In [23]:
print(a.shape)
reshaped = a.view(3, 1)
print(reshaped)
print(reshaped.shape)

torch.Size([3])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


In [22]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1], [2], [3]])
print(a.shape, b.shape)
result = a + b  # BROADCAST
print(result.shape)
print(result)

torch.Size([3]) torch.Size([3, 1])
torch.Size([3, 3])
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


In [24]:
matrix = torch.tensor([[1, 2], [3, 4]])
transposed_matrix = matrix.t()  # TRANSPOSE
print(transposed_matrix)

tensor([[1, 3],
        [2, 4]])


**⭐️ ACCESSING TENSORS**

In [25]:
tensor = torch.tensor([10, 20, 30, 40])
value = tensor[1] # SECOND ELEMENT
sliced_tensor = tensor[1:3]  # SLICE
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
value = matrix[1, 2]  # ELEMENT AT ROW 1, COLUMN 2 (6)

**⭐️ AUTOGRAD**

In [28]:
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x + 1
print(y.grad_fn)  # FUNCTION WHICH GENERATED y
y.backward()
print("Gradient of x:", x.grad)

Gradient of x: tensor([7.])
